### ISSUE TITLE
Achele - Single Listing Communty Page details

### ISSUE THREAD

**Issue by ibimina** [AritDeveloperCircle/findyourpeople#105]
<img width="346" alt="community details" src="https://github.com/AritDeveloperCircle/findyourpeople/assets/96787210/edb875f0-ae7c-421a-9309-f4296cf9878c">

**Comment by ibimina** [comment]
how is this going? any blockers

**Comment by Achele** [comment]
@ibimina I’m waiting for the Single listing community page to be merged. Need to work off that branch

**Comment by ibimina** [comment]
okay

**Comment by msarit** [comment]
ADOPTED! 🎉  @Achele leave the **Focus Areas** implementation out of this work, we do not have time to build that feature the way it should be.

**Comment by Achele** [comment]
Okay
