### ISSUE TITLE
Ibimina-Wireframing the Listing landing page

### ISSUE THREAD

**Issue by ibimina** [AritDeveloperCircle/findyourpeople#13]
Main display page/Listing landing page

Header: The header should contain the logo, navigation menu, and a search bar for users to find specific listings.

Banner: The banner should include a brief description of the community directory and its purpose. A clear CTA(Call to Action) should be included on the banner, inviting users to either create their own listing or explore the listings already available.

Categories and filters: The main section of the landing page should include a list of categories and filters that users can use to narrow down their search. 

Listing previews: Each listing preview should include a community name, community manager name, community description, and an image representing the listing.

Pagination: If there are a large number of listings, pagination should be used to break them up into smaller groups.

Footer: The footer should include logo and links to important pages, such as the About Us page, Contact Us page, and Terms of Use.

<img width="960" alt="list of listing page" src="https://user-images.githubusercontent.com/96787210/231568844-01489a55-1274-41a7-a760-2027649c015c.png">

**Comment by msarit** [comment]
This is beautiful work @ibimina!

Please ask your team members to weigh in on your wireframe, seeing as it is the app landing page.

**Comment by ibimina** [comment]
I will do that @msarit

**Comment by istoga** [comment]
I like the navbar, I think maybe having the community manager underneath each other, not side by side, and I appreciate the pagination. Is the bottom the footer? I don't know that you need a logo for the footer, but I think it is a good thing to place the navigation at the bottom too.

**Comment by ibimina** [comment]
@istoga I think it's a norm to have website logos at the footer and also the community listing would probably look better side by side(minimum of two) on the desktop view(large screen), in a mobile view we could stack them as you suggested to make  page responsive.
Thanks for the feedback.

**Comment by msarit** [comment]
@ibimina Hello Ibimina, could we update the center of the wireframe to include more Listings, instead of just 2?

**Comment by ibimina** [comment]
@msarit Okay, will do that
