### ISSUE TITLE
 Taylor- add functionality to the search input field

### ISSUE THREAD

**Issue by ibimina** [AritDeveloperCircle/findyourpeople#130]

**Comment by TaylorDJones11** [comment]
For clarification @ibimina, I'm adding the functionality to this search bar to filter through community listings? 
<img width="345" alt="Screenshot 2023-06-07 at 12 11 02" src="https://github.com/AritDeveloperCircle/findyourpeople/assets/72883059/031004f6-1ce0-40fa-90cd-9ce2f408d417">

**Comment by ibimina** [comment]
yes
