### ISSUE TITLE
Taylor - Wireframe  app aspects - Sign Up Page - Login In Page - Landing Page -   authenticated manager

### ISSUE THREAD

**Issue by TaylorDJones11** [AritDeveloperCircle/findyourpeople#14]
Here are the wireframes for the Manager's SignIn and Landing Page in a web view. I incorporated both @istoga's flowchart and @ibimina's wireframes. I did add a logout button as I wasn't sure what was supposed to be added in the "navigation" component. Please add input, if you think anything should be changed, added, or deleted. 

Add in the Sign Up page

![Create an account](https://user-images.githubusercontent.com/72883059/232430948-3e2d2424-4832-4263-bcb6-8c60477cc521.png)

![Manager Login](https://user-images.githubusercontent.com/72883059/232430936-762626f8-f2d6-49cf-a5bb-335ccfb7f65e.png)
![Manager Landing Page](https://user-images.githubusercontent.com/72883059/231514784-065fda14-929b-4733-9ff0-a7df9992b8f9.png)

**Comment by msarit** [comment]
Sounds good @TaylorDJones11! 🎉

Seeing as you have not updated this ticket with any diagrams or descriptions, please update the ticket status in the Project Board to "In Progress". Thanks!

**Comment by TaylorDJones11** [comment]
![Manager Landing Page](https://user-images.githubusercontent.com/72883059/230744048-86d885ea-cd4e-43d1-b8da-9f00b203bb59.png)

**Comment by msarit** [comment]
@TaylorDJones11 Create Desktop View
Also incorporate Neka's [Flow work](https://github.com/AritDeveloperCircle/findyourpeople/issues/10) into your wireframe

**Comment by istoga** [comment]
I appreciate the cleanness of your wireframing @TaylorDJones11, can't wait to see the manger workflow added.

**Comment by ibimina** [comment]
I love your wireframes, I was not sure of the external pages to be present that's why I just added the navigation component, perhaps Ms. Justine would help out during our Friday meeting. 
Good job

**Comment by TaylorDJones11** [comment]
Thanks! I'll wait until Friday to see if any changes should be made

**Comment by msarit** [comment]
DONE.
