### ISSUE TITLE
The links "Contact" and "Terms Of Use" in the Footer do not go anywhere

### ISSUE THREAD

**Issue by msarit** [AritDeveloperCircle/findyourpeople#155]
The links "Contact" and "Terms Of Use" in the Footer do not go anywhere

![Screen Shot 2023-06-21 at 12 31 27 PM](https://github.com/AritDeveloperCircle/findyourpeople/assets/32520970/ca48f8cf-52cd-4eae-928c-c7cba6eef136)

**Comment by TaylorDJones11** [comment]
This has been merged
