### ISSUE TITLE
Remove Home and SignUp links that were used for debugging

### ISSUE THREAD

**Issue by msarit** [AritDeveloperCircle/findyourpeople#156]
They appear on the Login and SignUp pages (see below):

![Screen Shot 2023-06-21 at 12 34 22 PM](https://github.com/AritDeveloperCircle/findyourpeople/assets/32520970/95d25c8a-8f49-4b95-9597-cb97527c028d)

![Screen Shot 2023-06-21 at 12 33 40 PM](https://github.com/AritDeveloperCircle/findyourpeople/assets/32520970/dc295ae9-919e-4ad6-bff3-3919e2302431)

**Comment by TaylorDJones11** [comment]
This has been merged
