### ISSUE TITLE
Taylor- Fixing Login Page Bugs

### ISSUE THREAD

**Issue by TaylorDJones11** [AritDeveloperCircle/findyourpeople#166]
Fixing Login Page to match the styles of the Sign up page

**Comment by ibimina** [comment]
@TaylorDJones11 can you fix the listing image bug on the landing page some are bigger than the others

**Comment by TaylorDJones11** [comment]
> @TaylorDJones11 can you fix the listing image bug on the landing page some are bigger than the others, also we don't have a contact page but there is a link for it
> 
> 

Sure, fixing it now.

**Comment by ibimina** [comment]
ok, one more thing the link to an view a community external url "visit communtiy" in a single community page should be  a tag with target blank

**Comment by TaylorDJones11** [comment]
> @TaylorDJones11 can you fix the listing image bug on the landing page some are bigger than the others, also we don't have a contact page but there is a link for it

Contact in the navbar? I pulled it out on my last PR 
<img width="1360" alt="Screenshot 2023-06-26 at 15 26 15" src="https://github.com/AritDeveloperCircle/findyourpeople/assets/72883059/a769feb6-2104-44f3-9936-44a95b478248">

**Comment by ibimina** [comment]
uhmm maybe its just in @istoga branch
