### ISSUE TITLE
Chibuzo: Wireframing the different aspects of the app to show functionality

### ISSUE THREAD

**Issue by Domicaren1** [AritDeveloperCircle/findyourpeople#18]

**Comment by istoga** [comment]
@Domicaren1 looking forward to seeing your wireframe for app functionality.

**Comment by ibimina** [comment]
@Domicaren1 what part of the app functionality wireframe are you working on?

**Comment by istoga** [comment]
@Domicaren1 please let us know if you need help finishing this out, or if you are unsure about anything.

**Comment by Domicaren1** [comment]
@istoga I wasn't so sure of how to go about it. But from yesterday's meeting I think all the needed wireframes have been done.

**Comment by msarit** [comment]
Closing this issue; no work to be done.
