### ISSUE TITLE
seyi update readMe with my name

### ISSUE THREAD

**Issue by Sheyitofunmi** [AritDeveloperCircle/findyourpeople#24]
I added my name

**Comment by msarit** [comment]
@Sheyitofunmi Where is your Pull Request? I do not see it under "Pull Requests" so how did you add your name?

**Comment by Sheyitofunmi** [comment]
I just added it ma

**Comment by ibimina** [comment]
@Sheyitofunmi move your issue/ticket status from In progress to ready for review
