### ISSUE TITLE
Seyi - UX /Flow plan for User or Community manager 

### ISSUE THREAD

**Issue by Sheyitofunmi** [AritDeveloperCircle/findyourpeople#27]
1. Landing page: When a user visits the app, they are presented with a landing page that briefly explains what the app does and how to use it. The landing page contains a clear call-to-action (CTA) button to "Explore Communities."  It clearly communicate the purpose of the app and encourage users to explore the directory. It  also provide a search bar and filtering options to help users find the communities they're interested in, They also see a brief description of what the app does.

- Registration/Login: Users should be able to register for an account or log in using their email or social media accounts. This will allow them to submit new listings, suggest labels, and save their favorite communities.

-  Search Bar: Once a user starts searching for communities, they should be taken to a search page. Here, they can filter their search results by tags or other relevant criteria, such as community size or activity level.They should be able to browse the directory of communities. The page should display the listings in a clear and organized manner, with sorting and filtering options available to help users find what they're looking for. Each listing should display the community's name, description, tags, and any other relevant information

-  User Profile: Users can create an account to save their favorite listings, view their submission history, and receive notifications about their listings' approval status ,They can also view and edit their profile information, including their saved favorites and any listings they have submitted.

-  Edit or remove listing: Listing owners can edit or remove their listings at any time. They can do this by logging into their account and making the necessary changes. The changes will then be sent to the directory owner for approval..

-  Notifications: Users will receive notifications when their listing is approved or rejected, when a label suggestion is approved or rejected, and when there are updates to their saved favorites.

 2. View Community Details: Clicking on a button from Landing page takes the user to the community's Profile page. This page displays     information about the community, including its name, description, tags, approval status, and any other relevant details including social media accounts or websites links.The page also includes a CTA button to a "Form"  for community managers to add their Listing.

-  Help/Support: The help/support section of the app where users can find answers to common questions, contact support,   and provide feedback.

3. Listing Form: This form  ask for information such as the community's name, description, size, and any relevant tags.  It  also allow the user to provide contact information in case the directory owner needs to get in touch with them.Once submitted, the community will be added to a queue for approval by the directory owners.

4. Community Approval: Once a community is submitted, it is added to a queue for approval by the directory owners. The owners can view a list of pending submissions and either approve or reject them. If the community is approved, it will be added to the public directory and can be viewed by all users. If it is rejected, the submitter will receive an explanation and  can resubmit with revisions.

5. Suggesting Labels: Community managers can suggest labels for their listings, but the directory owner will need to approve them before they are added. 

6. Tag Management: Directory owners can manage the tags associated with each community. They can view a list of all the tags currently in use and add or remove tags as needed. Community managers can suggest new tags for their communities, but the owners have the final say on whether to add them or not.

![IMG_20230414_080134](https://user-images.githubusercontent.com/99263653/231983501-67bd7d6a-daf9-4626-bd64-2fa65052e43d.jpg)

**Comment by ibimina** [comment]
@Sheyitofunmi The UX/Flow above is for user/community manager , your ticket says UX/Flow is in respect to the App Owner.

**Comment by Sheyitofunmi** [comment]
I have done that, thank you ibimina

**Comment by TaylorDJones11** [comment]
@Sheyitofunmi We already have the UX flow and wireframes for Community Manager. Here are Neka's wireframes that have been adopted https://github.com/AritDeveloperCircle/findyourpeople/issues/10 . Here are the wireframes I created for that UX flow.  https://github.com/AritDeveloperCircle/findyourpeople/issues/14  https://github.com/AritDeveloperCircle/findyourpeople/issues/15 . We are in need of a UX flow/ wireframes for the App Owner and I believe the App User. I'm sure this will be more clear after today's meeting.

**Comment by ibimina** [comment]
> I have done that, thank you ibimina

I didn't  mean that you should rename your issue, the UX flow you should work on is that of the App Owner

**Comment by Sheyitofunmi** [comment]
Okay, I am going to work on the UX flow for app owerners

**Comment by istoga** [comment]
Hey @Sheyitofunmi let us know if you need a had with anything.

**Comment by msarit** [comment]
DONE.
