### ISSUE TITLE
Neka-Listing Components For App (SP: 2)

### ISSUE THREAD

**Issue by istoga** [AritDeveloperCircle/findyourpeople#29]
Listing the components required for the application

1. NavBar => Logo, Search Bar, Navigation
2. Main Content
- Listing => Single Listing
- General
- Manager
- Owner
- Avatar
- Button
- Login Form
- Signup Form
- Pagination
4. Footer => Logo, Navigation

STORY POINTS: 2

*Please add comments in order to build this out with anything else that may be missing.

**Comment by TaylorDJones11** [comment]
@Neka Nice setup! Maybe a component for a Single Listing?

**Comment by istoga** [comment]
I will add it, thanks @TaylorDJones11

**Comment by Achele** [comment]
This is great @istoga! maybe a component for each CRUD actions and also the community labels

**Comment by ibimina** [comment]
@istoga  Pagination component

**Comment by ibimina** [comment]
@istoga The components that are being listed are they for all the wireframes or a single wireframe?

**Comment by istoga** [comment]
Thanks everyone for your comments, they are very helpful!

**Comment by msarit** [comment]
DONE.
