### ISSUE TITLE
Seyi - Login Page Components

### ISSUE THREAD

**Issue by Sheyitofunmi** [AritDeveloperCircle/findyourpeople#32]
This login page components is going to include  the Button components, Aside Component and Avatar Component.

**Comment by ibimina** [comment]
@Sheyitofunmi please clarify are developing the login page or the components

**Comment by Sheyitofunmi** [comment]
I am developing the login page @ibimina

**Comment by msarit** [comment]
@Sheyitofunmi I think it may be a better approach to start with the discrete components first, before building the components that will import these discrete compoenents.

@jjleigh please weigh in. I believe you gave this advice during Sprint 3 Planning.

**Comment by Sheyitofunmi** [comment]
okay ma, will take note of that
