### ISSUE TITLE
Achele - Footer Component (Comprises of Logo Component and Navigation Component)

### ISSUE THREAD

**Issue by Achele** [AritDeveloperCircle/findyourpeople#36]
1. Coding the Footer to include the logo and navigation.
2. Navigation includes sections for About, Contact and Terms of Use.

**Comment by Achele** [comment]
1. Coding the Footer to include the logo and navigation.
2. Navigation includes sections for About, Contact and Terms of Use.

**Comment by ibimina** [comment]
@Achele move your issue description from the comment to the issue box

**Comment by Achele** [comment]
Okay @ibimina will do.
