### ISSUE TITLE
Ibimina - Firebase Integration

### ISSUE THREAD

**Issue by ibimina** [AritDeveloperCircle/findyourpeople#38]
### Firebase Integration

- install firebase package
- create a firebase folder in the src folder
- create a config.js file
- initialize firebase
- export firestore, auth variable
- create a .env file at root directory and store keys
- add .env to .gitignore file

**Comment by TaylorDJones11** [comment]
Hey @ibimina checking to see if you want to complete this ticket or is open for anyone. I'm looking to practice my PRs and get familiar with Firebase.

**Comment by ibimina** [comment]
@TaylorDJones11 I have completed it already, but you will still have to install firebase and store the api keys in the .env file in your local machine
