### ISSUE TITLE
Taylor - Manager Single Community Component

### ISSUE THREAD

**Issue by ibimina** [AritDeveloperCircle/findyourpeople#50]
This comprises of avatar component, button component(edit, view, unpublish, delete), community name
Check [Manager landing page ](#14 )  wireframe for more reference

Component Screenshot
<img width="158" alt="manager single community component" src="https://user-images.githubusercontent.com/96787210/233671421-34cc940e-5edb-455e-845f-f8f75dea1ece.png">

**Comment by TaylorDJones11** [comment]
Hey @ibimina for the image, it was just an image that could be their logo or an image representing their community. I don't have a name for the component yet but I'll swap it out with Avatar Component once I do.

**Comment by ibimina** [comment]
Okay, No problem

**Comment by TaylorDJones11** [comment]
@ibimina how can I connect this ticket to my latest PR?

**Comment by TaylorDJones11** [comment]
> @TaylorDJones11 you will have to add a hashtag # to your ticket number

Thanks!
