### ISSUE TITLE
Neka-Manager Community Dashboard

### ISSUE THREAD

**Issue by ibimina** [AritDeveloperCircle/findyourpeople#51]
This comprises of  Manager Single Community Component, button component

Component Screenshot

<img width="313" alt="update dashboard" src="https://github.com/AritDeveloperCircle/findyourpeople/assets/96787210/2ac80244-2ce5-4b39-ba15-647e7c32ca93">

**Comment by TaylorDJones11** [comment]
@istoga I've  just created a PR for the Manager Single Community. I'm sure you can't get much done without it being merged, but hopefully soon 🤞🏾

**Comment by ibimina** [comment]
@istoga you moved this to blocked?

**Comment by istoga** [comment]
Yes, but it should have been moved beyond that. Sorry, will move tonight.
