### ISSUE TITLE
Neka-Style Navbar on Landing Page with Tailwind CSS

### ISSUE THREAD

**Issue by istoga** [AritDeveloperCircle/findyourpeople#71]
Utilize Tailwind to develop Landing Page

**Comment by istoga** [comment]
If any team member would like to help develop this out, feel free to assign yourself. TIA!

**Comment by Domicaren1** [comment]
Ok @istoga .

**Comment by istoga** [comment]
Thanks sounds great, but I see you made another PR? I think we only need one.
