### ISSUE TITLE
Guard Managers Route and Add Listing Route

### ISSUE THREAD

**Issue by ibimina** [AritDeveloperCircle/findyourpeople#97]
We need to enhance the security of our platform by implementing route guards for the managers' and community listing creation routes. Currently, the managers' routes are accessible without any authentication, which poses a security risk.

Acceptance Criteria:

- Implement route guards to restrict access to the managers' routes.
- Only authenticated managers should be able to access the managers' routes.
- The listing creation route should be accessible to authenticated managers.
- Unauthorized access attempts to the managers' routes should result in an appropriate error response (e.g., 401 Unauthorized or 403 Forbidden).

**Comment by msarit** [comment]
@ibimina for security reasons, I think an unauthorized attempt should return 404; 403 signals that there is a resource there. @annonymousauthority what do you think? I defer to your counsel 😅

**Comment by ibimina** [comment]
Okay
